### ISSUE TITLE
Save ggarrange?

### ISSUE THREAD

**Issue by nhamilton1980** [baptiste/egg#3]
Babtiste, this package is awesome. So useful.

Is it possible to 'save' a ggarrange object, just like it is possible to save a ggplot object, so it can be loaded later?

OR 

Is it limited to writing to the viewport at the moment the call is executed?

If the former is not available, can I be so bold to put it on the roadmap, as it would be invaluable in my opinion.

**Comment by baptiste** [comment]
If you assign the result to a variable and use draw = FALSEI believe  it should do what you want,

```
library(egg)

grid.newpage()
g <- ggarrange(ggplot(),ggplot(), draw = FALSE)
grid.draw(g)
```

**Comment by nhamilton1980** [comment]
Thanks.

At the moment ggarrange returns object of type: "gtable" "gTree"  "grob"   "gDesc" ,

It would be good if this could inherit from something like 'egg', ie  'egg',"gtable" "gTree"  "grob"   "gDesc", so a print S3 method could be written to run grid.draw. 

Dunno, you probably see problems with this approach, but for me, I'm thinking of just being able to load the objects from disk and running print, so whether the plots are ggplot2 objects, or egg objects, the same behaviour results.

**Comment by nhamilton1980** [comment]
So I have a package that I use that contains custom functions that I use frequently, anyway, I put the following definitions in it.

```

#' Create Egg Object (NEH)
#'
#' Overrides the ggarrange method from the egg package, to expose the S3 method for printing
#' @inheritParams egg::ggarrange
#' @export
ggarrange = function(...,
                     plots   = list(...),
                     nrow    = NULL,
                     ncol    = NULL,
                     widths  = NULL,
                     heights = NULL,
                     byrow   = TRUE,
                     debug   = FALSE){
  args          = as.list(environment())
  args$newpage  = FALSE
  args$draw     = FALSE
  result        = do.call(egg::ggarrange,args=args)
  class(result) = c('egg',class(result))
  result
}

```
```

#' @rdname ggarrange
#' @usage NULL
#' @format NULL
#' @export
print.egg = function(x,...){
  gridExtra::grid.arrange(x,...)
}

```

**Comment by baptiste** [comment]
I don't know what you mean to do with this print method but FYI I added one last week

**Comment by nhamilton1980** [comment]
Oh cool. Just updated. I can delete the above code, because what your update does exactly what I wanted.

**Comment by nhamilton1980** [comment]
After installing the latest version, I noticed that the print S3 method is marked as export in the roxygen decorations, but it is not added to Namespace, and can only be accessed via egg:::print.egg(x) meaning that it has no actual purpose for anyone loading egg library via library(egg) command.

**Comment by baptiste** [comment]
should be fixed now, for some reason my Rstudio project wasn't set up to run roxygen

**Comment by nhamilton1980** [comment]
Thanks. Yep works. Cheers.

**Comment by nhamilton1980** [comment]
There is a problem in the print function, the use of `grid.newpage()` inserts an unwanted page at the start when printing to device such as `pdf(...)`.
